apiVersion: v1
kind: Secret
metadata:
  name: scaffold-backend-secrets
type: Opaque
stringData:
  DB_USERNAME: "root"
  DB_PASSWORD: "rootpassword"
  DB_DATABASE: "scaffolldb"
  REDIS_HOST: "redis"
  S3_BUCKET: "your-bucket"
  S3_REGION: "ap-south-1"
  S3_ACCESS_KEY_ID: "<ACCESS_KEY>"
  S3_SECRET_ACCESS_KEY: "<SECRET>"
  JWT_SECRET: "<jwt-secret>"
  JWT_REFRESH_SECRET: "<refresh-secret>"
  SMTP_USER: "no-reply@example.com"
  SMTP_PASS: "<smtp-pass>"
